# Generated by Django 3.2.7 on 2021-09-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(blank=True, default='Sri Selvi Sweets', max_length=300)),
                ('price_in_dollars', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
